### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'O2S.Components.PDF4NET.NET'

### ISSUE THREAD

**Issue by hojjatnikan** [o2solutions/pdf4net#9]
Description:
I encountered an issue while trying to run my application. The following exception was thrown:

System.IO.FileNotFoundException: 'Could not load file or assembly 'O2S.Components.PDF4NET.NET, Version=14.1.1.0, Culture=neutral, PublicKeyToken=80d03dd9e5b85317'. The system cannot find the file specified.'

Expected Behavior:
The application should load the 'O2S.Components.PDF4NET.NET' assembly without any issues.
This issue did not occur in version 14.1.0 of the PDF4NET library.

Actual Behavior:
The application throws a System.IO.FileNotFoundException indicating that the 'O2S.Components.PDF4NET.NET' assembly could not be found.

Environment:
•  .NET Version: .Net8.0

•  PDF4NET Version: 14.1.1.0

**Comment by pdf4dev-solutions-support** [comment]
This might be a cache problem. Please clear the solution and then rebuild. If you still have problems, remove the reference to PDF4NET package and add a new reference to PDF4NET 14.1.1.0 evaluation nuget package and then rebuild.

**Comment by hojjatnikan** [comment]
Thank you for your suggestion. 
I have uploaded a sample for you to test. Please check it out.

[WinFormsApp1.zip](https://github.com/user-attachments/files/16344164/WinFormsApp1.zip)

**Comment by pdf4dev-solutions-support** [comment]
Thank you for the sample application. We'll investigate it and get back to you with the results.

**Comment by pdf4dev-solutions-support** [comment]
The issue appears because test.csproj is a generic .NET project and nuget resolver selects the O2S.Components.PDF4NET.NET.dll for build but the WinFormsApp1.csproj is a specific Windows .NET project and nuget resolver selects the O2S.Components.PDF4NET.NET.Win.dll in the final output. Set the <TargetFramework> in test.csproj to net8.0-windows8.0 (`<TargetFramework>net8.0-windows8.0</TargetFramework>`) and the application will run.

**Comment by hojjatnikan** [comment]
thanks
